name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: build
    environment:
      GITHUB_PAGES_URL: ${{ steps.build-publish.outputs.page_url }}